In [1]:
import numpy as np

np.zeros(3)

array([0., 0., 0.])

In [2]:
np.ones((3,2)) # 3 rows, 2 columns

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [3]:
np.array([1, 2, 3]) # 1 row

array([1, 2, 3])

In [4]:
my_array = np.array([[1, 2, 3], [4, 5, 6]]) # 2 rows
print(my_array)

[[1 2 3]
 [4 5 6]]


In [5]:
my_array.shape

(2, 3)

In [6]:
my_array.shape = (6, 1)
print(my_array)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [7]:
other_array = np.linspace(2, 6, 5) # from 2 to 6, 3 values in total
print(other_array)

[2. 3. 4. 5. 6.]


In [8]:
simple_array = np.array([1, 2, 3])
print(simple_array + 2)

[3 4 5]


In [9]:
simple_array * 3

array([3, 6, 9])

In [10]:
simple_array + simple_array

array([2, 4, 6])

In [11]:
simple_array * simple_array

array([1, 4, 9])

In [12]:
simple_array @ simple_array.T # dot product

14

In [13]:
print("Sum", np.sum(simple_array))
print("Mean", np.mean(simple_array))
print("Std", np.std(simple_array))
print("Min", np.min(simple_array))
print("Max", np.max(simple_array))
print("Argmin", np.argmin(simple_array))
print("Argmax", np.argmax(simple_array))

Sum 6
Mean 2.0
Std 0.816496580927726
Min 1
Max 3
Argmin 0
Argmax 2


In [14]:
# Comparison
simple_array < 3

array([ True,  True, False])

In [16]:
np.where(simple_array < 3, 10, 0) # where smaller than 3, set 10, 0 otherwise

array([10, 10,  0])

In [17]:
simple_array[:2]

array([1, 2])